spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

server:
  port: 8080

application:
  locale: en
  execution.flag: true
  confirm.exit.flag: true
  number.right.answers.for.positive.result: 4
  csv.question.file.url: resources/TestQuestions.csv
