spring:
  main:
    allow-circular-references: true

  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false

    command:
      version:
        enabled: false

  data:
    mongodb:
      host: localhost
      port: 27017
      database: library

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: 388082
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.homework.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    d: WARN
    o: WARN


