spring:
  main:
    allow-circular-references: true

  batch:
    job:
      enabled: false

  data:
    mongodb:
      host: localhost
      port: 0
      database: library

  datasource:
    url: jdbc:h2:mem:library
    driverClassName: org.h2.Driver
    username: user
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.homework.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
